from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField, JSONField
from django.db.models import Model, CharField, DateTimeField, ForeignKey, IntegerField, CASCADE
from django.utils.crypto import get_random_string


class Channel(Model):
    """Represents content channel"""
    url = CharField(max_length=2048)
    selector = CharField(max_length=512)
    title = CharField(max_length=512)
    slug = CharField(max_length=32, editable=False, null=False, unique=True)     # autogenerated field for use in URLs
    extractors = JSONField(null=False, default=dict, blank=True)        # TODO: Document this structure

    def save(self):
        if not self.id:     # new channel
            self.slug = Channel.make_slug()

        super(Channel, self).save()

    @classmethod
    def make_slug(cls):
        while True:
            slug = get_random_string(length=32)
            if not cls.objects.filter(slug=slug).exists():
                break
        return slug

    def __str__(self):
        return self.title


class Entry(Model):
    """Represents content entry"""
    channel = ForeignKey(Channel, on_delete=CASCADE)
    added = DateTimeField('date added')
    title = CharField(max_length=512)
    url = CharField(max_length=2048)    # url as seen in channel
    final_url = CharField(max_length=2048, null=True)   # url after all redirects etc, null if equals to original url
    items = JSONField(null=True)        # TODO: Document this structure

    def __str__(self):
        return self.title

