language: python
python:
 - "3.5"

dist: trusty
sudo: false

services:
  - postgresql: "9.5"

 # command to install dependencies
install: "pip install -r requirements.txt"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

env:
  global:
    - DATABASE_URL='postgresql://postgres@localhost/travis_ci_test'
    - SECRET_KEY='Not really a secret'

# command to run tests
script:  make test
