language: python
cache: pip

python:
 - "3.5"

dist: trusty
sudo: false

services:
  - postgresql

addons:
  postgresql: "9.5"

 # command to install dependencies
install:
  - "pip install -r requirements/base.txt"
  - "pip install -r requirements/test.txt"

before_script:
  - psql -t -c 'select version()' -U postgres
  - psql -c 'create database travis_ci_test;' -U postgres
  - python manage.py migrate

env:
  global:
    - DATABASE_URL='postgresql://postgres@localhost/travis_ci_test'
    - SECRET_KEY='Not really a secret'

# command to run tests
script: coverage run manage.py test --keepdb

after_success:
  - codecov
