language: python
python:
 - "3.5"

services: postgresql

 # command to install dependencies
install: "pip install -r requirements.txt"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

env:
  - DATABASE_URL='postgresql://postgres@localhost/travis_ci_test'

# command to run tests
script:  make test
