# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 17:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('interval', models.CharField(choices=[
                 ('MAN', 'Manual'), ('10M', 'Every 10 minutes'), ('1H', 'Every hour'), ('1D', 'Every day')], default='1D', max_length=3)),
                ('enabled', models.BooleanField(default=True)),
                ('url', models.URLField(max_length=2048)),
                ('slug', models.CharField(editable=False, max_length=32, unique=True)),
                ('row_selector', models.CharField(max_length=512)),
                ('url_selector', models.CharField(max_length=512)),
                ('title_selector', models.CharField(max_length=512)),
                ('extra_selector', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('url', models.URLField(max_length=2048)),
                ('title', models.CharField(max_length=512)),
                ('extra', models.CharField(blank=True, max_length=2048)),
                ('final_url', models.URLField(blank=True, max_length=2048)),
                ('items', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webscraper.Channel')),
            ],
        ),
    ]
