# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 19:10
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2048)),
                ('selector', models.CharField(max_length=512)),
                ('title', models.CharField(max_length=512)),
                ('adapters', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(verbose_name='date added')),
                ('title', models.CharField(max_length=512)),
                ('url', models.CharField(max_length=2048)),
                ('final_url', models.CharField(max_length=2048, null=True)),
                ('items', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webscraper.Channel')),
            ],
        ),
    ]
