# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 23:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='adapters',
        ),
        migrations.AddField(
            model_name='channel',
            name='extractors',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
