# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='extra_selector',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
