# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 03:08
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0002_auto_20170306_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='items',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
