# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0002_auto_20170228_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='slug',
            field=models.CharField(default='', editable=False, max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
