# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 20:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0003_channel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='extractors',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
