# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0003_auto_20170407_2334'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set([('channel', 'url')]),
        ),
    ]
